review/superheroes/config/routes.rb
Rails.application.routes.draw do
  root 'heroes#list'

  get 'heroes/batman', as: "batman"

  get 'heroes/superman', as: "superman"

end

review/superheroes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

review/superheroes/app/controllers/heroes_controller.rb
class HeroesController < ApplicationController
  def list
  end

  def batman
  end

  def superman
  end
end

review/superheroes/app/helpers/application_helper.rb
module ApplicationHelper
end

review/superheroes/app/helpers/heroes_helper.rb
module HeroesHelper
end

review/superheroes/app/views/heroes/_hero.html.erb
<div class="hero">
    
  <div class="page-header">
    <h1><%= name %> <small>Subtext for header</small></h1>
  </div>


  <%= image_tag "#{name}.jpg", class: "img-responsive" %>

</div>

review/superheroes/app/views/heroes/batman.html.erb
<%= render partial: 'hero', locals: {name: "batman"} %>

review/superheroes/app/views/heroes/list.html.erb
<h1>Heroes#list</h1>

<ul>
  <li><%= link_to 'Superman rules', superman_path %></li>
  <li><%= link_to 'No Way, Batman is much better', batman_path %></li>
</ul>

<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <%= render partial: 'hero', locals: {name: "batman"} %>
    </div>

    <div class="col-xs-3">
      <%= render partial: 'hero', locals: {name: "superman"} %>
    </div>

  </div>
</div>

review/superheroes/app/views/heroes/superman.html.erb
<%= render partial: 'hero', locals: {name: "superman"} %>

review/superheroes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superheroes</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= link_to 'Home', root_path %>

  <%= yield %>

</body>
</html>